---
name: cicd-matrix
"on":
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.matrix.outputs.output }}
    steps:
      - uses: actions/checkout@v3
      - uses: fabasoad/data-format-converter-action@main
        id: matrix
        with:
          input: ".github/workflows/matrix.yml"
          from: "yaml"
          to: "json"

  test:
    runs-on: ${{ matrix.runs-on }}
    needs: [prepare-matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible core
        run: pip install ansible-core==${{ matrix.ansible-core-version }}

      - name: ghcr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: ./run.sh ci-test
