---
name: fjson
"on":
  workflow_dispatch:

jobs:
  matrix_prep:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(jq -c . < matrix.json)" >> $GITHUB_OUTPUT
      # - run: echo '${{ fromJson(env.PACKAGE_JSON).version }}'
  test-matrix-from-json:
    runs-on: ubuntu-22.04
    needs: [matrix_prep]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
