name: Release new candidate version

"on":
  workflow_dispatch:
    inputs:
      branch_name:
        description: "branch name to create"
        required: true
        type: string
env:
  GOVER: 1.18.4

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set env vars
        run: |
          echo "BRANCH_NAME=${{ inputs.branch_name }}" >> $GITHUB_ENV

      - name: Run target
        run: |
          make publish-files
